/**
 * ORDVAL — Order Validation Module (Modernized)
 *
 * Generated by Tarsius from approved business rules in .bob/RISK-CONTEXT.md.
 * Source: sample-data/ORDVAL.rpgle (last modified 2015-03-22 by J. Hendricks)
 *
 * Approved rules implemented:
 *   BR-CANCELLED-BLOCK       — Cancelled accounts cannot submit orders
 *   BR-SUSPENDED-BLOCK       — Suspended accounts are blocked from orders
 *   BR-DISC-EXCEPTION        — Suspended accounts may submit DISC orders
 *   BR-GRANDFATHER-PRICING   — Plan-7 legacy customers retain locked-in pricing
 *
 * ⚠️  GOTCHA GOT-001 (CRITICAL / LEGAL):
 *   BR-DISC-EXCEPTION and BR-GRANDFATHER-PRICING reference class action
 *   settlements CS-4471 (2010) and 2009-CV-118. These rules are legally
 *   binding. Never remove or disable them without explicit legal sign-off.
 *
 * ⚠️  GOTCHA GOT-002 (HIGH / BUSINESS):
 *   Plan-7 legacy pricing grandfathering must be preserved per 2009 class
 *   action. Never remove the grandfathering branch for PLAN7.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type OrderType = "STND" | "DISC" | "EXPR" | "CORP";
export type ValidationResult = "A" | "R"; // A = Approved, R = Rejected

export interface CustomerData {
  /** Account status: 'C' = Cancelled, 'S' = Suspended, others = Active */
  custStatus: string;
  /**
   * Whether the suspended-account DISC exception applies.
   * Set to 'Y' for accounts covered under CS-4471 (2010 class action).
   */
  suspendedFlag: string;
  /** Pricing plan identifier. 'PLAN7' triggers legacy locked-in pricing. */
  planId: string;
}

export interface PricingData {
  /** Legacy locked-in price (PLAN7 / 2009-CV-118 settlement). */
  legacyPrice: number;
  /** Standard current-rate price. */
  standardPrice: number;
}

export interface ValidationOutput {
  result: ValidationResult;
  /** Resolved base price after pricing rules are applied. */
  basePrice: number;
}

// ─── Business Rule: BR-CANCELLED-BLOCK ───────────────────────────────────────

/**
 * BR-CANCELLED-BLOCK — Cancelled accounts cannot submit orders.
 *
 * Source: code + document (spec v3.2 §2.1). No contradictions.
 * Confidence: high.
 *
 * "Accounts with status C (Cancelled) are rejected for all order types."
 *   — order-validation-spec.md §2.1
 */
function isCancelledAccount(custStatus: string): boolean {
  return custStatus === "C";
}

// ─── Business Rule: BR-SUSPENDED-BLOCK ───────────────────────────────────────

/**
 * BR-SUSPENDED-BLOCK — Suspended accounts are blocked from orders.
 *
 * Source: code + document (spec v3.2 §2.2). Base rule agrees with spec.
 * Confidence: high.
 *
 * ⚠️  CONTRADICTION NOTE: The spec (§2.2) states "No exceptions exist for
 * suspended accounts under any order type." This is false — see
 * BR-DISC-EXCEPTION below, which overrides this rule for DISC orders
 * under CS-4471. The spec was never updated after the 2010 amendment.
 * Treat the CODE as the source of truth for suspended accounts.
 */
function isSuspendedAccount(custStatus: string): boolean {
  return custStatus === "S";
}

// ─── Business Rule: BR-DISC-EXCEPTION ────────────────────────────────────────

/**
 * BR-DISC-EXCEPTION — Suspended accounts MAY submit DISC orders.
 *
 * Source: CODE ONLY — not documented in spec (implicit rule).
 * Confidence: high (code).
 * Triage: 🔴 must-review (contradiction with spec §2.2).
 *
 * ⚠️  GOTCHA GOT-001 (CRITICAL / LEGAL):
 *   This exception was introduced by ticket CS-4471 as part of a 2010
 *   class action settlement. DO NOT REMOVE without explicit legal sign-off.
 *   The spec says "No exceptions exist" — that statement is incorrect and
 *   predates CS-4471. The code is the authoritative source here.
 */
function isDiscExceptionEligible(
  suspendedFlag: string,
  orderType: OrderType
): boolean {
  return suspendedFlag === "Y" && orderType === "DISC";
}

// ─── Business Rule: BR-GRANDFATHER-PRICING ───────────────────────────────────

/**
 * BR-GRANDFATHER-PRICING — Plan-7 customers retain locked-in legacy pricing.
 *
 * Source: CODE ONLY — spec §3.2 actively contradicts this rule.
 * Confidence: high (code).
 * Triage: 🟡 glance (code-only, no doc support).
 *
 * ⚠️  GOTCHA GOT-001 (CRITICAL / LEGAL):
 *   Locked pricing for PLAN7 was mandated by class action settlement
 *   2009-CV-118. DO NOT REMOVE without explicit legal sign-off.
 *
 * ⚠️  GOTCHA GOT-002 (HIGH / BUSINESS):
 *   Plan-7 legacy pricing grandfathering must be preserved per 2009 class
 *   action. Never route PLAN7 customers to standard pricing.
 *
 * ⚠️  CONTRADICTION NOTE: spec §3.2 states "Legacy plan migrations were
 *   retired as of 2012… Special pricing arrangements for Plan 7 customers
 *   are no longer supported." This is incorrect — the settlement overrides
 *   the documentation. The spec footnote itself acknowledges this divergence.
 */
function resolveBasePrice(planId: string, pricing: PricingData): number {
  if (planId === "PLAN7") {
    // Class action settlement 2009-CV-118 — locked pricing applies.
    return pricing.legacyPrice;
  }
  return pricing.standardPrice;
}

// ─── Main Validation Entry Point ──────────────────────────────────────────────

/**
 * validateOrder — Validates a customer order before processing.
 *
 * Implements all 4 approved business rules from .bob/RISK-CONTEXT.md:
 *   BR-CANCELLED-BLOCK, BR-SUSPENDED-BLOCK, BR-DISC-EXCEPTION,
 *   BR-GRANDFATHER-PRICING.
 *
 * Returns `A` (approved) or `R` (rejected), along with the resolved price.
 */
export function validateOrder(
  customer: CustomerData,
  orderType: OrderType,
  pricing: PricingData
): ValidationOutput {
  // BR-CANCELLED-BLOCK: Cancelled accounts always rejected.
  if (isCancelledAccount(customer.custStatus)) {
    return { result: "R", basePrice: 0 };
  }

  // BR-SUSPENDED-BLOCK: Suspended accounts rejected …
  if (isSuspendedAccount(customer.custStatus)) {
    // … unless BR-DISC-EXCEPTION applies (CS-4471 class action, 2010).
    // ⚠️ GOTCHA GOT-001: DO NOT remove this override without legal sign-off.
    if (isDiscExceptionEligible(customer.suspendedFlag, orderType)) {
      const basePrice = resolveBasePrice(customer.planId, pricing);
      return { result: "A", basePrice };
    }
    return { result: "R", basePrice: 0 };
  }

  // BR-GRANDFATHER-PRICING: resolve price (PLAN7 gets locked legacy rate).
  // ⚠️ GOTCHA GOT-001 + GOT-002: DO NOT change PLAN7 routing without legal.
  const basePrice = resolveBasePrice(customer.planId, pricing);
  return { result: "A", basePrice };
}
