import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Plugin, Connect } from "vite";

// ---------------------------------------------------------------------------
// Paths (Workspace-First Resolution)
// ---------------------------------------------------------------------------

const ROOT = resolve(__dirname, "..");
const WORKSPACE = process.env.TARSIUS_WORKSPACE || process.cwd();

function resolveWorkspaceFile(candidates: string[], fallback: string): string {
  for (const rel of candidates) {
    const p = resolve(WORKSPACE, rel);
    if (existsSync(p)) return p;
  }
  return fallback;
}

const BRI_PATH = resolveWorkspaceFile(
  [
    ".tarsius/bri.json",
    ".tarsius/tarsius-bri.json",
    ".bob/tarsius-bri.json",
    "sample-data/tarsius-bri.json",
    "tarsius-bri.json",
  ],
  resolve(ROOT, "sample-data/tarsius-bri.json")
);

const DECISIONS_PATH = resolveWorkspaceFile(
  [
    ".tarsius/decisions.json",
    ".tarsius/tarsius-decisions.json",
    ".bob/tarsius-decisions.json",
    "sample-data/tarsius-decisions.json",
    "tarsius-decisions.json",
  ],
  resolve(ROOT, "sample-data/tarsius-decisions.json")
);

const RISK_CONTEXT_PATH = resolveWorkspaceFile(
  [".bob/RISK-CONTEXT.md", ".tarsius/RISK-CONTEXT.md"],
  resolve(ROOT, ".bob/RISK-CONTEXT.md")
);

const GOTCHAS_PATH = resolveWorkspaceFile(
  [
    ".tarsius/gotchas.json",
    ".tarsius/tarsius-gotchas.json",
    ".bob/tarsius-gotchas.json",
    "sample-data/tarsius-gotchas.json",
    "tarsius-gotchas.json",
  ],
  resolve(ROOT, "sample-data/tarsius-gotchas.json")
);

const SAMPLE_DATA_DIR = resolve(ROOT, "sample-data");
const PUBLICS_DIR = resolve(ROOT, "publics");

// ---------------------------------------------------------------------------
// SHA-256 helpers
// ---------------------------------------------------------------------------

function sha256(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

// ---------------------------------------------------------------------------
// RISK-CONTEXT.md generator
// ---------------------------------------------------------------------------

interface BriRule {
  id: string;
  title: string;
  description: string;
  category: string;
  triage: string;
  riskScore: number;
  approvalStatus: "approved" | "pending" | "rejected";
  evidence: {
    contradiction: boolean;
    contradictionNote?: string;
    docQuote: string | null;
  };
}

interface BriDocument {
  rules: BriRule[];
}

function regenerateRiskContext(bri: BriDocument): void {
  const approved = bri.rules.filter((r) => r.approvalStatus === "approved");
  const pending = bri.rules.filter((r) => r.approvalStatus === "pending");
  const rejected = bri.rules.filter((r) => r.approvalStatus === "rejected");

  const lines: string[] = [
    "# RISK-CONTEXT",
    "",
    "> Auto-generated by Tarsius approvePlugin. Do not edit manually.",
    `> Last updated: ${new Date().toISOString()}`,
    "",
  ];

  // Approved section
  lines.push("## ✅ Approved Rules");
  lines.push("");
  if (approved.length === 0) {
    lines.push("_No approved rules._");
  } else {
    for (const r of approved) {
      lines.push(`### ${r.id} — ${r.title}`);
      lines.push(`- **Category**: ${r.category}`);
      lines.push(`- **Triage**: ${r.triage}`);
      lines.push(`- **Risk score**: ${r.riskScore}`);
      lines.push(`- **Description**: ${r.description}`);
      lines.push("");
    }
  }

  // Pending section
  lines.push("## 🕐 Pending Rules");
  lines.push("");
  if (pending.length === 0) {
    lines.push("_No pending rules._");
  } else {
    for (const r of pending) {
      const contradictionMarker = r.evidence.contradiction
        ? " ⚠️ CONTRADICTION"
        : "";
      lines.push(`### ${r.id} — ${r.title}${contradictionMarker}`);
      lines.push(`- **Category**: ${r.category}`);
      lines.push(`- **Triage**: ${r.triage}`);
      lines.push(`- **Risk score**: ${r.riskScore}`);
      lines.push(`- **Description**: ${r.description}`);
      if (r.evidence.contradiction && r.evidence.contradictionNote) {
        lines.push(
          `- **⚠️ Contradiction note**: ${r.evidence.contradictionNote}`
        );
      }
      lines.push("");
    }
  }

  // Rejected section
  lines.push("## ❌ Rejected Rules");
  lines.push("");
  if (rejected.length === 0) {
    lines.push("_No rejected rules._");
  } else {
    for (const r of rejected) {
      lines.push(`### ${r.id} — ${r.title}`);
      lines.push(`- **Category**: ${r.category}`);
      lines.push(`- **Description**: ${r.description}`);
      lines.push("");
    }
  }

  writeFileSync(RISK_CONTEXT_PATH, lines.join("\n"), "utf8");
}

// ---------------------------------------------------------------------------
// Body reader helper
// ---------------------------------------------------------------------------

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((res, rej) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => chunks.push(chunk));
    req.on("end", () => res(Buffer.concat(chunks).toString("utf8")));
    req.on("error", rej);
  });
}

// ---------------------------------------------------------------------------
// Static file middleware helper
// ---------------------------------------------------------------------------

function serveStatic(
  urlPrefix: string,
  dir: string
): Connect.NextHandleFunction {
  return (req, res, next) => {
    const url = req.url ?? "";
    if (!url.startsWith(urlPrefix)) return next();

    const relativePath = url.slice(urlPrefix.length).split("?")[0];
    const cleanRel = relativePath.replace(/^\//, "");

    // Check user workspace first (.tarsius/ or .bob/ or sample-data/ or root), then fall back to dir
    const candidates = [
      resolve(WORKSPACE, ".tarsius", cleanRel),
      resolve(WORKSPACE, ".tarsius", cleanRel.replace(/^tarsius-/, "")),
      resolve(WORKSPACE, ".bob", cleanRel),
      resolve(WORKSPACE, "sample-data", cleanRel),
      resolve(WORKSPACE, cleanRel),
      resolve(dir, cleanRel),
    ];

    let filePath: string | null = null;
    for (const cand of candidates) {
      if (existsSync(cand)) {
        filePath = cand;
        break;
      }
    }

    if (!filePath || !existsSync(filePath)) return next();

    let body: Buffer;
    try {
      body = readFileSync(filePath);
    } catch {
      return next();
    }

    const ext = filePath.split(".").pop() ?? "";
    const mime: Record<string, string> = {
      json: "application/json",
      js: "application/javascript",
      ts: "text/plain",
      css: "text/css",
      html: "text/html",
      png: "image/png",
      svg: "image/svg+xml",
    };
    res.setHeader("Content-Type", mime[ext] ?? "application/octet-stream");
    res.end(body);
  };
}

// ---------------------------------------------------------------------------
// POST /api/approve handler
// ---------------------------------------------------------------------------

async function handleApprove(
  req: IncomingMessage,
  res: ServerResponse
): Promise<void> {
  let body: { ruleId: string; decision: string; justification?: string };
  try {
    const raw = await readBody(req);
    body = JSON.parse(raw);
  } catch {
    res.writeHead(400, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ success: false, error: "Invalid JSON body" }));
    return;
  }

  const { ruleId, decision, justification = "" } = body;
  if (!ruleId || !decision) {
    res.writeHead(400, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({ success: false, error: "ruleId and decision are required" })
    );
    return;
  }

  // Load and mutate BRI
  const bri: BriDocument & {
    rules: (BriRule & Record<string, unknown>)[];
  } = JSON.parse(readFileSync(BRI_PATH, "utf8"));

  const ruleIndex = bri.rules.findIndex((r) => r.id === ruleId);
  if (ruleIndex === -1) {
    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ success: false, error: `Rule ${ruleId} not found` }));
    return;
  }

  const previousStatus = bri.rules[ruleIndex].approvalStatus;
  bri.rules[ruleIndex].approvalStatus = decision as "approved" | "pending" | "rejected";
  writeFileSync(BRI_PATH, JSON.stringify(bri, null, 2), "utf8");

  // Load decisions and compute chain
  const decisionsDoc: {
    version: string;
    decisions: Record<string, unknown>[];
    summary: {
      totalDecisions: number;
      approved: number;
      rejected: number;
      reversed: number;
      overrides: number;
    };
    lastChainHash: string;
  } = JSON.parse(readFileSync(DECISIONS_PATH, "utf8"));

  const timestamp = new Date().toISOString();
  const userId = "architect-1";

  // Genuine SHA-256 hashes
  const hash = sha256(`${ruleId}${timestamp}${userId}${justification}`);
  // Treat any all-zero string (regardless of length) as the genesis seed
  const lastChainHash =
    decisionsDoc.lastChainHash && !/^0+$/.test(decisionsDoc.lastChainHash.trim())
      ? decisionsDoc.lastChainHash
      : "0".repeat(64);
  const chainHash = sha256(`${lastChainHash}${hash}`);

  const decisionId = `DEC-${String(
    decisionsDoc.decisions.length + 1
  ).padStart(5, "0")}`;

  const newDecision = {
    id: decisionId,
    hash,
    chainHash,
    ruleId,
    decision: {
      previousStatus,
      newStatus: decision,
    },
    decidedBy: {
      userId,
      userName: "Architect",
      role: "architect",
    },
    timestamp,
    justification: justification || "",
    context: {
      overrideAutoApprove: false,
      reversed: false,
      riskScoreAtDecision: bri.rules[ruleIndex].riskScore,
      triageAtDecision: bri.rules[ruleIndex].triage,
    },
  };

  decisionsDoc.decisions.push(newDecision);
  decisionsDoc.lastChainHash = chainHash;

  // Update summary counts
  if (decision === "approved") decisionsDoc.summary.approved += 1;
  if (decision === "rejected") decisionsDoc.summary.rejected += 1;
  decisionsDoc.summary.totalDecisions += 1;

  writeFileSync(DECISIONS_PATH, JSON.stringify(decisionsDoc, null, 2), "utf8");

  // Regenerate RISK-CONTEXT.md
  regenerateRiskContext(bri as BriDocument);

  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ success: true, ruleId, hash, chainHash }));
}

// ---------------------------------------------------------------------------
// approvePlugin — custom Vite plugin
// ---------------------------------------------------------------------------

function approvePlugin(): Plugin {
  return {
    name: "tarsius-approve-plugin",
    configureServer(server) {
      // Serve sample-data JSON files
      server.middlewares.use(serveStatic("/sample-data", SAMPLE_DATA_DIR));

      // Serve publics files
      server.middlewares.use(serveStatic("/publics", PUBLICS_DIR));

      // GET /api/bri
      server.middlewares.use(
        "/api/bri",
        (req: IncomingMessage, res: ServerResponse, next: Connect.NextFunction) => {
          if (req.method !== "GET") return next();
          try {
            const data = readFileSync(BRI_PATH, "utf8");
            res.setHeader("Content-Type", "application/json");
            res.end(data);
          } catch {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "BRI document not found" }));
          }
        }
      );

      // GET /api/decisions
      server.middlewares.use(
        "/api/decisions",
        (req: IncomingMessage, res: ServerResponse, next: Connect.NextFunction) => {
          if (req.method !== "GET") return next();
          try {
            const data = readFileSync(DECISIONS_PATH, "utf8");
            res.setHeader("Content-Type", "application/json");
            res.end(data);
          } catch {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Decisions document not found" }));
          }
        }
      );

      // GET /api/gotchas
      server.middlewares.use(
        "/api/gotchas",
        (req: IncomingMessage, res: ServerResponse, next: Connect.NextFunction) => {
          if (req.method !== "GET") return next();
          try {
            const data = readFileSync(GOTCHAS_PATH, "utf8");
            res.setHeader("Content-Type", "application/json");
            res.end(data);
          } catch {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Gotchas document not found" }));
          }
        }
      );

      // Handle POST /api/approve
      server.middlewares.use(
        "/api/approve",
        (req: IncomingMessage, res: ServerResponse, next: Connect.NextFunction) => {
          if (req.method !== "POST") return next();
          handleApprove(req, res).catch((err: unknown) => {
            console.error("[approvePlugin] Error:", err);
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(
              JSON.stringify({ success: false, error: "Internal server error" })
            );
          });
        }
      );
    },
  };
}

// ---------------------------------------------------------------------------
// Vite config
// ---------------------------------------------------------------------------

export default defineConfig({
  base: "./",
  server: {
    port: 8321,
    strictPort: true,
  },
  plugins: [react(), tailwindcss(), approvePlugin()],
});
