import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { updateApprovalStatus, readBri } from "../bri/writer.js";
import { recordDecision } from "../bri/decision-store.js";
import { checkGotchas } from "../bri/gotcha-store.js";
import type { BusinessRule } from "../bri/schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
// Workspace root is three levels up: dist/tools -> dist -> mcp-server -> workspace root
const WORKSPACE_ROOT = resolve(__dirname, "../../../");
const RISK_CONTEXT_PATH = resolve(WORKSPACE_ROOT, ".bob/RISK-CONTEXT.md");

export interface MarkApprovedInput {
  ruleId: string;
  decision: "approved" | "rejected";
  justification?: string;
  userId?: string;
  userName?: string;
  role?: string;
}

export interface MarkApprovedResult {
  rule: BusinessRule;
  decisionId: string;
  riskContextRegenerated: boolean;
}

// ---------------------------------------------------------------------------
// RISK-CONTEXT.md generation
// ---------------------------------------------------------------------------

function ruleSection(rule: BusinessRule): string {
  const contraMarker = rule.evidence.contradiction
    ? " ⚠️ CONTRADICTION"
    : "";
  const lines: string[] = [
    `### ${rule.id} — ${rule.title}${contraMarker}`,
    "",
    `- **Type**: ${rule.type}`,
    `- **Category**: ${rule.category}`,
    `- **Triage**: ${rule.triage}  |  **Risk Score**: ${rule.riskScore}`,
    `- **Confidence**: ${rule.confidence.label} (${rule.confidence.score}) via ${rule.confidence.method}`,
    `- **Source**: ${rule.source.join(", ")}`,
    `- **Affects Modules**: ${rule.affectsModules.join(", ") || "—"}`,
    "",
    rule.description,
    "",
    `> **Code**: \`${rule.evidence.codeLocation.file}\` lines ${rule.evidence.codeLocation.startLine}–${rule.evidence.codeLocation.endLine}`,
  ];

  if (rule.evidence.docQuote) {
    lines.push(`> **Doc Quote**: "${rule.evidence.docQuote}"`);
  }

  if (rule.evidence.contradiction && rule.evidence.contradictionNote) {
    lines.push(``, `> ⚠️ **Contradiction**: ${rule.evidence.contradictionNote}`);
  }

  return lines.join("\n");
}

async function regenerateRiskContext(): Promise<void> {
  const doc = await readBri();

  const approved = doc.rules.filter((r) => r.approvalStatus === "approved");
  const pending = doc.rules.filter((r) => r.approvalStatus === "pending");
  const rejected = doc.rules.filter((r) => r.approvalStatus === "rejected");

  const sections: string[] = [
    "# RISK-CONTEXT",
    "",
    "> Auto-generated by Tarsius MCP Server. DO NOT EDIT MANUALLY.",
    `> Last updated: ${new Date().toISOString()}`,
    "",
    "---",
    "",
    "## Approved Rules",
    "",
    approved.length > 0
      ? approved.map(ruleSection).join("\n\n---\n\n")
      : "_No approved rules yet._",
    "",
    "---",
    "",
    "## Pending Rules",
    "",
    pending.length > 0
      ? pending.map(ruleSection).join("\n\n---\n\n")
      : "_No pending rules._",
    "",
    "---",
    "",
    "## Rejected Rules",
    "",
    rejected.length > 0
      ? rejected.map(ruleSection).join("\n\n---\n\n")
      : "_No rejected rules._",
    "",
  ];

  const content = sections.join("\n");
  await mkdir(resolve(WORKSPACE_ROOT, ".bob"), { recursive: true });
  await writeFile(RISK_CONTEXT_PATH, content, "utf-8");
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export async function handleMarkApproved(
  input: MarkApprovedInput
): Promise<MarkApprovedResult> {
  // 1. Read current rule to capture previousStatus and triage/risk context
  const doc = await readBri();
  const existing = doc.rules.find((r) => r.id === input.ruleId);
  if (!existing) {
    throw new Error(`Rule not found: ${input.ruleId}`);
  }

  const previousStatus = existing.approvalStatus;

  // 2. Update approval status in BRI
  const rule = await updateApprovalStatus(input.ruleId, input.decision);

  // 3. Record immutable decision entry
  const entry = await recordDecision({
    ruleId: input.ruleId,
    decision: input.decision,
    justification: input.justification ?? `${input.decision} via mark_approved`,
    previousStatus,
    decidedBy: {
      userId: input.userId,
      userName: input.userName,
      role: input.role,
    },
    context: {
      riskScoreAtDecision: rule.riskScore,
      triageAtDecision: rule.triage,
    },
  });

  // 4. Regenerate RISK-CONTEXT.md
  await regenerateRiskContext();

  return {
    rule,
    decisionId: entry.id,
    riskContextRegenerated: true,
  };
}
